
import com.ericsson.scd.DrawClass;
import junit.framework.TestCase;


/**
 * The class <code>DrawClassTest</code> contains tests for the class {@link
 * <code>DrawClass</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 10/12/11 9:08 AM
 *
 * @author evanmoh
 *
 * @version $Revision$
 */
public class DrawClassTest extends TestCase {

    /**
     * Construct new test instance
     *
     * @param name the test name
     */
    public DrawClassTest(String name) {
        super(name);
        
       
    }
    
    public void  testRenderDimensions()
    {
        DrawClass d1 = new DrawClass();
        
        
        
        
    }
    }


/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = 
 * package.sourceFolder = ThoughtworksDayTwo/src1
 * superclassType = junit.framework.TestCase
 * testCase = DrawClassTest
 * testClassType = com.ericsson.scd.DrawClass
 */